import type { MenuItem } from "./types";

const portion = (
  id: string,
  category: string,
  name: string,
  price: number,
  packageLabel: "盒" | "份" = "份",
  detail?: string,
): MenuItem => ({ id, category, name, price, unitKind: "portion", packageLabel, detail });

const pieces = (
  id: string,
  category: string,
  name: string,
  price: number,
  piecesPerPackage: number,
  detail?: string,
): MenuItem => ({
  id,
  category,
  name,
  price,
  piecesPerPackage,
  unitKind: "piece",
  packageLabel: "份",
  detail,
});

export const menu: MenuItem[] = [
  portion("pandan-layer-cake", "廣式蒸糕", "斑斕椰汁千層糕", 10, "盒"),
  portion("brown-sugar-layer-cake", "廣式蒸糕", "黑糖椰汁千層糕", 10, "盒"),
  portion("jujube-ginger-layer-cake", "廣式蒸糕", "紅棗薑汁千層糕", 10, "盒"),
  portion("thai-tea-layer-cake", "廣式蒸糕", "泰式奶茶千層糕", 10, "盒"),
  portion("sesame-layer-cake", "廣式蒸糕", "黑芝麻椰汁千層糕", 10, "盒"),
  portion("millet-red-bean-cake", "廣式蒸糕", "小米紅豆糕", 10, "盒"),
  portion("red-bean-coconut-cake", "廣式蒸糕", "紅豆椰汁／牛奶糕", 10, "盒"),
  portion("caramel-water-chestnut-cake", "廣式蒸糕", "焦糖馬蹄糕", 10, "盒"),
  portion("osmanthus-coconut-cake", "廣式蒸糕", "桂花椰汁糕", 10, "盒"),
  portion("passionfruit-coconut-cake", "廣式蒸糕", "百香果椰汁糕", 10, "盒"),
  portion("hawthorn-coconut-cake", "廣式蒸糕", "山楂椰汁糕", 10, "盒"),
  portion("sesame-film-roll", "廣式蒸糕", "黑芝麻菲林卷", 10, "盒"),
  portion("white-sugar-cake", "廣式蒸糕", "順德白糖糕（倫教糕）", 10, "盒"),
  portion("ma-lai-go", "廣式蒸糕", "古法馬拉糕", 10, "盒"),
  portion("honeycomb-cake", "廣式蒸糕", "迷你蜂巢糕", 10, "盒"),
  portion("turnip-cake", "廣式蒸糕", "廣式臘味蘿蔔糕", 10, "盒"),
  portion("taiwan-turnip-cake", "廣式蒸糕", "台式蝦米蘿蔔糕", 10, "盒"),
  portion("taro-cake", "廣式蒸糕", "廣式臘味芋頭糕", 10, "盒"),
  portion("coconut-new-year-cake", "廣式蒸糕", "紅糖椰汁年糕", 10, "盒"),
  portion("toffee-new-year-cake", "廣式蒸糕", "焦糖太妃年糕", 10, "盒"),
  pieces("put-chai-ko", "廣式蒸糕", "廣式缽仔糕", 10, 12, "紅豆、綠豆、提子乾、焦糖栗子"),
  portion("snow-cake", "夏季清涼糕點", "椰汁雪花涼糕", 10),
  portion("thai-tea-cold-cake", "夏季清涼糕點", "泰式奶茶涼糕", 10),
  portion("mung-bean-cold-cake", "夏季清涼糕點", "台式綠豆桂花涼糕", 10),
  portion("red-bean-cold-cake", "夏季清涼糕點", "台式紅豆黑糖涼糕", 10),
  portion("purple-rice-taro-cake", "夏季清涼糕點", "台式紫米芋泥涼糕", 10),
  pieces("icecream-mung-bean-cake", "夏季清涼糕點", "軟皮冰淇淋綠豆餅", 10, 10),
  pieces("oat-snow-cake", "夏季清涼糕點", "中山燕麥雪餅", 10, 8),
  portion("chicken-biscuit", "廣式傳統小吃", "傳統雞仔餅", 10, "份", "300g"),
  pieces("walnut-cookie", "廣式傳統小吃", "傳統桃酥", 10, 10),
  pieces("mung-bean-pastry", "廣式傳統小吃", "酥皮綠豆餅", 10, 8),
  portion("pandan-coconut-roll", "廣式傳統小吃", "馬拉斑斕椰絲卷", 15),
  pieces("hakka-mochi", "廣式傳統小吃", "客家糯米糍／艾糍", 10, 8, "花生芝麻、芋泥、紅豆、海苔肉鬆"),
  pieces("pistachio-mochi", "廣式傳統小吃", "開心果糯米糍", 15, 6),
  pieces("chocolate-mochi", "廣式傳統小吃", "朱古力榛子糯米糍", 15, 6),
  pieces("nut-mochi", "廣式傳統小吃", "堅果糯米糍三拼", 15, 6),
  pieces("ham-sui-gok", "廣式傳統小吃", "家鄉珍珠鹹水角", 15, 10),
  pieces("fried-dough-cake", "廣式傳統小吃", "鹹煎餅", 15, 8),
  pieces("sa-yung", "廣式傳統小吃", "糖沙翁（蛋球）", 15, 8),
  pieces("pork-floss-roll", "廣式傳統小吃", "肉鬆麵包卷", 15, 4),
  pieces("char-siu-bao", "廣式傳統小吃", "蔡瀾雪山叉燒包", 15, 8),
  pieces("pork-bun", "廣式傳統小吃", "北方鮮肉包子", 15, 8),
  pieces("jujube-cake", "廣式傳統小吃", "老式紅棗糕", 15, 9),
  pieces("scallion-roll", "廣式傳統小吃", "香蔥肉花卷", 10, 8),
  pieces("sesame-roll", "廣式傳統小吃", "黑芝麻花卷", 10, 8),
  portion("sticky-rice", "廣式傳統小吃", "廣式臘味糯米飯", 10, "份", "約800g"),
  portion("double-skin-milk", "糖水", "順德雙皮奶", 5),
  portion("herbal-jelly", "糖水", "廣西龜苓膏", 5),
  portion("coconut-jelly", "糖水", "雙色椰子凍", 5),
  portion("red-bean-soup", "糖水", "陳皮紅豆沙", 5),
  portion("mung-bean-soup", "糖水", "陳皮海帶綠豆沙", 5),
  portion("almond-pudding", "糖水", "杏仁奶凍", 5),
  portion("purple-rice-soup", "糖水", "紫米紅豆糖水", 5),
  portion("sesame-milk", "糖水", "黑芝麻燉奶", 5),
  portion("pepper-pork-soup", "廣式不辣鹹點", "胡椒豬肚湯", 15),
  portion("pork-knuckle", "廣式不辣鹹點", "滷味豬中蹄", 12, "盒"),
  portion("pork-ear", "廣式不辣鹹點", "滷味豬耳朵", 12, "盒"),
  portion("duck-wing", "廣式不辣鹹點", "滷味鴨翅膀", 12, "盒"),
  portion("soy-egg", "廣式不辣鹹點", "滷味雞蛋", 10, "盒"),
  portion("pork-intestine", "廣式不辣鹹點", "滷味豬腸", 12, "盒"),
];

export const menuById = new Map(menu.map((item) => [item.id, item]));