import type { GroupBuy, OrderRequest } from "./types";

let requestIndex = 0;
const request = (
  memberId: string,
  itemId: string,
  mode: OrderRequest["mode"],
  options: Omit<OrderRequest, "id" | "memberId" | "itemId" | "mode"> = {},
): OrderRequest => ({
  id: `request-${++requestIndex}`,
  memberId,
  itemId,
  mode,
  ...options,
});

export const seedGroupBuy: GroupBuy = {
  id: "groupbuy-001",
  name: "八月糕點團購",
  status: "draft",
  createdAt: "2026-08-13T12:00:00.000Z",
  updatedAt: "2026-08-13T12:00:00.000Z",
  members: [
    { id: "joyce", name: "Joyce" },
    { id: "judy", name: "Judy", note: "除星期六外，其他日子都可以" },
    { id: "anthony", name: "Anthony" },
    { id: "susan", name: "Susan", note: "全部可以 Share" },
    { id: "adrian", name: "Adrian" },
    { id: "alvin", name: "Alvin Leung", note: "可 Share" },
    { id: "sakura", name: "Sakura", note: "8 月 17 日或之後可交收" },
    { id: "michelle", name: "Michelle" },
    { id: "natalie", name: "Natalie" },
    { id: "ring", name: "Ring" },
  ],
  requests: [
    request("joyce", "ham-sui-gok", "share"),
    request("joyce", "sa-yung", "share"),
    request("joyce", "hakka-mochi", "share", { flavor: "芋泥／花生芝麻" }),
    request("joyce", "duck-wing", "share", { note: "可 Share 或獨食" }),
    request("joyce", "pork-ear", "share", { note: "可 Share 或獨食" }),
    request("judy", "pandan-layer-cake", "share", { minimum: 5, fixed: true }),
    request("judy", "duck-wing", "share", { minimum: 1 / 3, fixed: true }),
    request("judy", "pork-intestine", "share", { minimum: 1 / 3, fixed: true }),
    request("judy", "pork-bun", "share", { minimum: 2, fixed: true }),
    request("judy", "ham-sui-gok", "share", { minimum: 3, fixed: true }),
    request("judy", "sa-yung", "share", { minimum: 2, fixed: true }),
    request("judy", "hakka-mochi", "share", { minimum: 2, fixed: true, flavor: "海苔肉鬆" }),
    request("anthony", "pandan-layer-cake", "share"),
    request("anthony", "ham-sui-gok", "share"),
    request("anthony", "sa-yung", "share"),
    request("anthony", "taro-cake", "whole"),
    request("anthony", "hakka-mochi", "share", { flavor: "芋泥／花生芝麻", note: "Wing Share 芋泥" }),
    request("susan", "ham-sui-gok", "share", { minimum: 2, fixed: true }),
    request("susan", "sa-yung", "share", { minimum: 2, fixed: true }),
    request("susan", "thai-tea-cold-cake", "share"),
    request("susan", "pork-bun", "share"),
    request("susan", "hakka-mochi", "share", { flavor: "海苔肉鬆" }),
    request("susan", "chocolate-mochi", "share", { note: "Wing Share" }),
    request("adrian", "sa-yung", "whole"),
    request("adrian", "sticky-rice", "whole"),
    request("adrian", "hakka-mochi", "whole", { flavor: "海苔肉鬆" }),
    request("adrian", "taro-cake", "whole"),
    request("alvin", "pandan-layer-cake", "share"),
    request("alvin", "turnip-cake", "share"),
    request("alvin", "put-chai-ko", "share", { flavor: "紅豆" }),
    request("alvin", "purple-rice-taro-cake", "share"),
    request("alvin", "ham-sui-gok", "share"),
    request("alvin", "sa-yung", "share"),
    request("alvin", "pork-bun", "share"),
    request("alvin", "sticky-rice", "whole"),
    request("alvin", "pork-ear", "whole"),
    request("alvin", "pork-intestine", "whole"),
    request("alvin", "double-skin-milk", "whole"),
    request("sakura", "ham-sui-gok", "share"),
    request("sakura", "sa-yung", "share"),
    request("sakura", "sticky-rice", "whole"),
    request("sakura", "pepper-pork-soup", "whole"),
    request("sakura", "duck-wing", "share", { note: "可 Share 或獨食" }),
    request("sakura", "pork-intestine", "share", { note: "可 Share 或獨食" }),
    request("michelle", "sa-yung", "share"),
    request("michelle", "pandan-layer-cake", "share"),
    request("michelle", "put-chai-ko", "share", { flavor: "紅豆" }),
    request("michelle", "pepper-pork-soup", "whole"),
    request("michelle", "pork-intestine", "share"),
    request("michelle", "duck-wing", "share"),
    request("michelle", "pork-bun", "share"),
    request("michelle", "pork-ear", "share"),
    request("michelle", "double-skin-milk", "whole", { quantity: 2 }),
    request("natalie", "ham-sui-gok", "share", { minimum: 2, fixed: true }),
    request("natalie", "sa-yung", "share", { minimum: 2, fixed: true }),
    request("natalie", "hakka-mochi", "share", { minimum: 2, fixed: true, flavor: "海苔肉鬆" }),
    request("ring", "pandan-layer-cake", "share", { minimum: 5, fixed: true }),
    request("ring", "sesame-film-roll", "share", { minimum: 0.5, fixed: true }),
    request("ring", "ma-lai-go", "share", { minimum: 0.5, fixed: true }),
    request("ring", "pork-ear", "share", { minimum: 0.5, fixed: true }),
    request("ring", "sa-yung", "whole"),
    request("ring", "ham-sui-gok", "whole"),
    request("ring", "pork-intestine", "whole"),
  ],
};